insert into ankit88_yellowsquash.category (cat_id, created_by, creation_date, last_modified_by, last_modified_date, category_name, slug) values (1,'YS admin', now(), 'YS admin', now(), 'Gut Health', "gut_health"),(2,'YS admin', now(), 'YS admin', now(), 'Women Health', "women-health"),(3, 'YS admin', now(), 'YS admin', now(), 'Diets', "diets"),(4, 'YS admin', now(), 'YS admin', now(), 'Lifestyle', "lifestyle"),(5, 'YS admin', now(), 'YS admin', now(), 'Allergies', "allergies"),(6, 'YS admin', now(), 'YS admin', now(), 'Nutrition', "nutrition"),(7, 'YS admin', now(), 'YS admin', now(), 'Fitness', "fitness"),(8, 'YS admin', now(), 'YS admin', now(), 'Diabetes', "diabetes"),(9, 'YS admin', now(), 'YS admin', now(), 'Weight Loss', "weight-loss"),(10, 'YS admin', now(), 'YS admin', now(), 'Alternate Therapies', "alternate_therapies");
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (1, 'Gut Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (2, 'NLP', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (3, 'Kids Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (4, 'Lactating Mothers', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (5, 'Dairy Free', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (6, 'Water Therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (7, 'Herbal', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (8, 'Genetics', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (9, 'Nutrigenomics', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (10, 'Gluten Free', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (11, 'Motivational Speaker', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (12, 'Productivity Training', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (13, 'Social Cause', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (14, 'Reiki', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (15, 'Psychotherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (16, 'Organic Farming', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (17, 'Microgreens', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (18, 'Health Food', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (19, 'Allergies (gluten, dairy, etc)', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (20, 'Pilates', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (21, 'Stress Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (22, 'Executive Coach', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (23, 'Career Coach', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (24, 'Organic Food', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (25, 'Hormonal Imbalance', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (26, 'Testing Labs', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (27, 'Behavioral Therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (28, 'De-addiction', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (29, 'Balanced Meals', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (30, 'Ayurveda', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (31, 'Functional Medicine', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (32, 'Integrative Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (33, 'Healthy Desserts', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (34, 'Gastrointestinal (GI)', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (35, 'Yoga', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (36, 'Detox', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (37, 'Cardiovascular', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (38, 'Elderly Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (39, 'Raw Juices', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (40, 'Naturopathy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (41, 'Body Building', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (42, 'Fitness', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (43, 'Vegan', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (44, 'Hepatic Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (45, 'Sujok', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (46, 'Hormonal Imbalance', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (47, 'Leadership Training', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (48, 'PMS', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (49, 'Sports Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (50, 'Weight Loss', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (51, 'Hypertension', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (52, 'Acupuncture', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (53, 'Health Food', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (54, 'Hypnotherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (55, 'Aromatherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (56, 'Thyroid', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (57, 'Paleo Diet', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (58, 'Lifestyle Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (59, 'Color therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (60, 'Healthy Snacks', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (61, 'Pregnancy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (62, 'Gastrointestinal (GI)', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (63, 'Life Skills', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (64, 'Accupressure', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (65, 'Spiritual Healing', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (66, 'Kidney', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (67, 'Psychology', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (68, 'Keto Diet', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (69, 'Meditation', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (70, 'Homeopathy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (71, 'Raw Foods', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (72, 'Diabetes', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (73, 'PCOS', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.expertise (expertise_id, exp_name,creation_date,created_by,last_modified_date,last_modified_by) values (74, 'Public Health', now(), 'YS admin', now(), 'YS admin');

insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (1, 'Accupressure', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (2, 'Acupuncture', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (3, 'Allergies (gluten, dairy, etc)', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (4, 'Amino Acids', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (5, 'Anaemia ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (6, 'Anti - Pollution', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (7, 'Anti ageing', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (8, 'Anti- inflamatory', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (9, 'Anti-cancer', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (10, 'Anti-inflamatory', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (11, 'Anti-oxidant', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (12, 'Aromatherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (13, 'Ayurveda', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (14, 'Balanced Meals', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (15, 'Behavioral Therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (16, 'Better Digestion', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (17, 'Body Building', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (18, 'Bone Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (19, 'Brain Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (20, 'Breast Cancer', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (21, 'Calcium Rich', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (22, 'Cancer', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (23, 'Cancer Diet  ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (24, 'Cancer Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (25, 'Carbohydrates', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (26, 'Cardiovascular', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (27, 'Career Coach', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (28, 'Cholesterol ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (29, 'Color therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (30, 'Dairy Free', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (31, 'De-addiction', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (32, 'Detox', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (33, 'Diabetes', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (34, 'Diabetes Friendly', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (35, 'Diabetes Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (36, 'Elderly Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (37, 'Executive Coach', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (38, 'Fats ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (39, 'Fitness', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (40, 'Functional Medicine', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (41, 'Gastrointestinal (GI)', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (42, 'Genetics', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (43, 'Gluten Free', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (44, 'Good Hair', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (45, 'Good Skin', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (46, 'Gout/ Uric acid', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (47, 'Gut Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (48, 'Health Food', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (49, 'Healthy Desserts', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (50, 'Healthy Drink ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (51, 'Healthy Eating', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (52, 'Healthy Fats ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (53, 'Healthy Snacks', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (54, 'Heart Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (55, 'Hepatic Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (56, 'Herbal', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (57, 'High Fiber', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (58, 'Homeopathy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (59, 'Hormonal Imbalance', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (60, 'Hypertension', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (61, 'Hypertension friendly', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (62, 'Hypertension management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (63, 'Hypnotherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (64, 'Immunity Booster', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (65, 'Integrative Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (66, 'Iron ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (67, 'Iron Rich', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (68, 'Keto Diet', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (69, 'Kidney', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (70, 'Kids Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (71, 'Lactating mothers', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (72, 'Leadership Training', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (73, 'Life Skills', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (74, 'Lifestyle Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (75, 'Low Calories', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (76, 'Low Fat', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (77, 'Low Sodium', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (78, 'Meditation', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (79, 'Microgreens', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (80, 'Minerals ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (81, 'Motivational Speaker', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (82, 'Naturopathy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (83, 'NLP', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (84, 'Nutrigenomics', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (85, 'Nutrition for Seniors', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (86, 'Omega-3 rich', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (87, 'Omega-6 rich', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (88, 'Organic', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (89, 'Organic Farming', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (90, 'Organic Food', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (91, 'Overall Healthy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (92, 'Oxidative stress', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (93, 'Paleo Diet', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (94, 'PCOS', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (95, 'Pilates', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (96, 'PMS', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (97, 'Prebiotic', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (98, 'Pregnancy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (99, 'Pregnancy Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (100, 'Preteen nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (101, 'Probiotic', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (102, 'Productivity Training', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (103, 'Protein Rich', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (104, 'Proteins ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (105, 'Psychology', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (106, 'Psychotherapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (107, 'Raw Foods', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (108, 'Raw Juices', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (109, 'Reiki', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (110, 'Salads', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (111, 'Saturated fat ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (112, 'Skin health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (113, 'Social Cause', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (114, 'Spiritual Healing', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (115, 'Sports Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (116, 'Stress ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (117, 'Stress Management', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (118, 'Sujok', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (119, 'Teenage Nutrition', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (120, 'Testing Labs', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (121, 'Thyroid', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (122, 'Tuberculosis', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (123, 'Vegan', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (124, 'Vegetarian', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (125, 'Vitamins ', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (126, 'Water Therapy', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (127, 'Weight Loss', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (128, 'Yoga', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (129, 'Lactose Intolerance', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (130, 'Glycemic Index', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (131, 'Arthiritis', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (132, 'Osteoporosis', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (133, 'Eye Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (134, 'Joint Pain', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (135, 'Smoking', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (136, 'Lung Health', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (137, 'Asthma', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (138, 'Bronchitis', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (139, 'COPD', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (140, 'Intermittent Fasting', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (141, 'Fasting', now(), 'YS admin', now(), 'YS admin');
insert into ankit88_yellowsquash.tags (tag_id, tag_name,creation_date,created_by,last_modified_date,last_modified_by) values (142, 'Public Health', now(), 'YS admin', now(), 'YS admin');

insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Abkhaz', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Afar', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Afrikaans', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Akan', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Albanian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Amharic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Arabic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Aragonese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Armenian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Assamese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Avaric', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Avestan', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Aymara', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Azerbaijani', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bambara', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bashkir', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Basque', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Belarusian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bengali', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bihari', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bislama', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bosnian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Breton', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Bulgarian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Burmese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Catalan; Valencian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Chamorro', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Chechen', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Chichewa; Chewa; Nyanja', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Chinese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Chuvash', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Cornish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Corsican', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Cree', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Croatian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Czech', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Danish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Divehi; Dhivehi; Maldivian;', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Dutch', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('English', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Esperanto', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Estonian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ewe', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Faroese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Fijian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Finnish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('French', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Fula; Fulah; Pulaar; Pular', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Galician', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Georgian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('German', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Greek, Modern', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Guaraní', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Gujarati', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Haitian; Haitian Creole', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Hausa', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Hebrew (modern)', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Herero', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Hindi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Hiri Motu', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Hungarian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Interlingua', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Indonesian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Interlingue', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Irish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Igbo', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Inupiaq', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ido', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Icelandic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Italian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Inuktitut', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Japanese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Javanese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kalaallisut, Greenlandic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kannada', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kanuri', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kashmiri', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kazakh', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Khmer', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kikuyu, Gikuyu', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kinyarwanda', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kirghiz, Kyrgyz', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Komi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kongo', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Korean', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kurdish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kwanyama, Kuanyama', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Latin', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Luxembourgish, Letzeburgesch', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Luganda', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Limburgish, Limburgan, Limburger', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Lingala', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Lao', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Lithuanian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Luba-Katanga', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Latvian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Manx', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Macedonian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Malagasy', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Malay', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Malayalam', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Maltese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Māori', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Marathi (Marāṭhī)', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Marshallese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Mongolian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Nauru', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Navajo, Navaho', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Norwegian Bokmål', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('North Ndebele', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Nepali', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ndonga', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Norwegian Nynorsk', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Norwegian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Nuosu', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('South Ndebele', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Occitan', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ojibwe, Ojibwa', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Oromo', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Oriya', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ossetian, Ossetic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Panjabi, Punjabi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Pāli', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Persian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Polish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Pashto, Pushto', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Portuguese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Quechua', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Romansh', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Kirundi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Romanian, Moldavian, Moldovan', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Russian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sanskrit (Saṁskṛta)', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sardinian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sindhi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Northern Sami', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Samoan', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sango', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Serbian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Scottish Gaelic; Gaelic', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Shona', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sinhala, Sinhalese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Slovak', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Slovene', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Somali', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Southern Sotho', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Spanish; Castilian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Sundanese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Swahili', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Swati', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Swedish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tamil', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Telugu', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tajik', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Thai', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tigrinya', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tibetan Standard, Tibetan, Central', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Turkmen', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tagalog', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tswana', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tonga (Tonga Islands)', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Turkish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tsonga', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tatar', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Twi', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Tahitian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Uighur, Uyghur', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Ukrainian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Urdu', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Uzbek', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Venda', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Vietnamese', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Volapük', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Walloon', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Welsh', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Wolof', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Western Frisian', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Xhosa', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Yiddish', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Yoruba', now(), 'YS Admin', now(), 'YS Admin');
insert into ankit88_yellowsquash.language (language_name,creation_date,created_by,last_modified_date,last_modified_by) values ('Zhuang, Chuang', now(), 'YS Admin', now(), 'YS Admin');